name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: [macos-latest]

    steps:
     - name: Select latest Xcode
       run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
       env:
        XC_VERSION: ${{ '12.2' }}
     - uses: actions/checkout@v2
     
     - name: Build
       run: swift build
     - name: Run tests
       run: swift test
