name: Swift

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name:  Build
      run: Unit_TestCase_Demo build -v
    - name: Run tests
      run: swift test -v
