name: ImplementTestCase

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:

    runs-on: [macos-11.2]
    
    env:
      XC_VERSION: ${{ '12.5' }}
      XC_WORKSPACE: ${{ 'iOSAPP.xcworkspace' }}
      XC_SCHEME: ${{ 'iOSAPP' }}
      XC_CONFIGURATION: ${{ 'Debug' }}
      XC_ARCHIVE_PATH: ${{ './iOSAPP.xcarchive' }}
      XC_EXPORT_PATH: ${{ './artifacts/' }}
      XC_EXPORT_OPTIONS_FILE_PATH: ${{ './ExportOptions.plist' }}

    steps:
    - uses: actions/checkout@v1


