name: Swift

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Force Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.4.1.app
      
    - name: build 
      uses: sersoft-gmbh/xcodebuild-action@v1.8.0
      
    - name: Xcode Test  
      uses: devbotsxyz/xcode-test@v1.1.0
      
