name: Swift

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Force Xcode 11
      run: sudo xcode-select -switch /Applications/Xcode_11.5.app
    - name: GitHub Action for `swift test`
      uses: 417-72KI/action-swift-test@master
