name: ImplementTestCase

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:

    runs-on: [macos-10.5]
    
    env:
      XC_VERSION: ${{ '12.5' }}
      XC_WORKSPACE: ${{ 'iOSAPP.xcworkspace' }}
      XC_SCHEME: ${{ 'iOSAPP' }}
      XC_CONFIGURATION: ${{ 'Debug' }}
      XC_ARCHIVE_PATH: ${{ './iOSAPP.xcarchive' }}
      XC_EXPORT_PATH: ${{ './artifacts/' }}
      XC_EXPORT_OPTIONS_FILE_PATH: ${{ './ExportOptions.plist' }}
      ENCRYPTED_CERTS_FILE_PATH: ${{ './github_action_dev_certificate_12345.p12.gpg' }}
      DECRYPTED_CERTS_FILE_PATH: ${{ './github_action_dev_certificate_12345.p12' }}
      ENCRYPTED_PROVISION_FILE_PATH: ${{ './provisioning.tar.gz.gpg' }}
      DECRYPTED_PROVISION_FILE_PATH: ${{ './provisioning.tar.gz' }}
      CERTS_ENCRYPTION_PWD: ${{ secrets.CERTS_ENCRYPTION_PWD }}
      PROVISION_ENCRYPTION_PWD: ${{ secrets.PROVISION_ENCRYPTION_PWD }}
      CERTS_EXPORT_PWD: ${{ secrets.CERTS_EXPORT_PWD }}
      KEYCHAIN: ${{ 'test.keychain' }}

    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - uses: actions/checkout@v2
    - name: Configure Keychain
      run: |
        security create-keychain -p "" "$KEYCHAIN"
        security list-keychains -s "$KEYCHAIN"
        security default-keychain -s "$KEYCHAIN"
        security unlock-keychain -p "" "$KEYCHAIN"
        security set-keychain-settings
        security list-keychains


