name: Swift

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Force Xcode 11
        run: sudo xcode-select -switch /Applications/Xcode_11.7.app
      - name: iOS build setup
        run: >-
          xcodebuild test -workspace ImplementTestCase.xcodeproj/project.xcworkspace
          -scheme ImplementTestCase -destination 'platform=iOS Simulator,name=iPhone
          11,OS=13.7'
