name: CI on Push and Pull Request

on: [push]

jobs:
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        cd Unit_TestCase_Demo
         name: Run unit tests
         run: xcodebuild test -scheme Unit_TestCase_Demo -workspace Unit_TestCase_Demo.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.2' | xcpretty && exit ${PIPESTATUS[0]}
