name: CI on Push and Pull Request

on: [push]

jobs:
  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run tests
      run: xcodebuild -project 'ImplementTestCase.xcodeproj' -scheme 'ImplementTestCase' -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.2' clean test

