name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Force Xcode 11
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
    - name: Run tests
      run: xcodebuild clean test -project "Unit_TestCase_Demo.xcodeproj" -scheme "Unit_TestCase_Demo" -destination "platform=iOS Simulator,name=iPhone 11 Pro Max,OS=latest"

