name: Swift

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: GitHub Action for `swift test`
        uses: 417-72KI/action-swift-test@master
